version: '3'

networks:
  tickdocker_public:
    external: true

services:
  telegraf:
    image: telegraf:1.7
    restart: unless-stopped
    volumes:
      - ./etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/utmp:/var/run/utmp
    expose:
      - "8092"
      - "8094"
      - "8125"
    networks:
      - tickdocker_public
