version: '3'

volumes:
  tick_data:

networks:
  private:
  public:

services:

  influxdb:
    image: influxdb:1.5
    restart: unless-stopped
    volumes:
      - tick_data:/var/lib/influxdb
      - ./certs/influxdb:/etc/ssl/influxdb
      - ./etc/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - "8086:8086"
    networks:
     - private
     - public

  chronograf:
    image: chronograf:1.5
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 8888
      BASE_PATH: /chronograf
      INFLUXDB_URL: https://influxdb:8086
      #INFLUXDB_USERNAME: admin
      #INFLUXDB_PASSWORD: admin123
      KAPACITOR_URL: http://kapacitor:9092
    depends_on:
      - influxdb
      - kapacitor
    volumes:
      - tick_data:/var/lib/chronograf
    #command: chronograf --host 0.0.0.0 --port 8888 --basepath /chronograf --influxdb-url=https://influxdb:8086 --kapacitor-url=http://kapacitor:9092 --influxdb-username=admin --influxdb-password=admin123
    expose:
      - "8888"
    networks:
     - private
     - public

  kapacitor:
    image: kapacitor:1.5
    restart: unless-stopped
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_LOAD_DIR: /etc/kapacitor/load
    depends_on:
      - influxdb
    expose:
      - "9092"
    volumes:
      - ./certs/influxdb:/etc/ssl/influxdb
      - ./etc/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
      - ./bin/task_status.sh:/usr/local/bin/task_status
      - ./etc/kapacitor/load:/etc/kapacitor/load
      - tick_data:/logs
      - tick_data:/var/lib/kapacitor
    command: kapacitord -config /etc/kapacitor/kapacitor.conf
    networks:
     - private
