apiVersion: v1
kind: LimitRange
metadata:
  name: mem-cpu-lr
  namespace: tick
spec:
  limits:
  - type: Container
    default:
      memory: 512Mi
      cpu: 1
    defaultRequest:
      memory: 256Mi
      cpu: 0.5
    max:
      memory: 1Gi
      cpu: "1000m"
    min:
      memory: 500Mi
      cpu: "500m"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-rq
  namespace: tick
spec:
  hard:
    requests.memory: 1Gi
    limits.memory: 2Gi
    requests.cpu: "1"
    limits.cpu: "2"
